### PR TITLE
add a 2013 booking

### PR DESCRIPTION
**Pull request by dimidd**
In http://pgexercises.com/questions/aggregates/fachoursbymonth2.html:
A query that doesn't check starttime is still considered correct, since there are no bookings after 2012. e.g.:
select facid, extract(month from starttime) as month, sum(slots)
from cd.bookings
group by facid, month
order by facid, month;

### CODE REVIEW

**Comment by AlisdairO** [comment]
Hey, thanks for the PR - I'll take a look and check that this modification doesn't impact any of the other exercises when I can.  I may be a while, though - I have a three week old who is occupying a ot of my attention at the moment, so my apologies if it takes me some time to merge!

**Comment by AlisdairO** [comment]
Hey - I noticed this doesn't actually use a 2013 date, so I pushed my own fix.  I realised as I pushed it I should have asked you to alter your PR - I'm very sorry!

**Comment by dimidd** [comment]
No problem, thanks for fixing :)

**Comment by AlisdairO** [comment]
Cheers :)

**Pull request closed without merging**
